### ISSUE TITLE
Support for HSL Color Highlighting in CSS Variables

### ISSUE THREAD

**Issue by iamshubhamjangle** [mattbierner/vscode-color-info#45]
I see a lot of projects using CSS variables to define colors with HSL values, especially in modern CSS files. For example:

```css
@layer base {
  :root {
    --background: 0 0% 100%;
    --foreground: 222.2 84% 4.9%;
  }
}
```
Currently, it seems the extension doesn't highlight these HSL values, even though they are valid and widely used.

Question:
Is this currently supported by the extension? If not, could we add support for highlighting HSL values defined in CSS variables? This feature would be incredibly useful for projects relying on modern CSS practices.

Thank you for your work on this extension!
